concierge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import URLPattern, URLResolver, include, path, re_path
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog
from oauth2_provider import views as oauth2_views
from oidc_provider.views import ProviderInfoView
from two_factor.urls import urlpatterns as tf_urls

from api import views as api_views
from core import views
from core.class_views import (
    IDPLoginView,
    Login2faView,
    PasswordLoginView,
    PasswordResetConfirmView,
    PasswordResetView,
    PrimaryLoginView,
    SamlConnectLoginView,
    SessionDeleteOtherView,
    SessionDeleteView,
)
from core.oidc import views as oidc_views
from saml import views as saml_views


class DecoratedURLPattern(URLPattern):
    def resolve(self, *args, **kwargs):
        result = super(DecoratedURLPattern, self).resolve(*args, **kwargs)
        if result:
            result.func = self._decorate_with(result.func)
        return result


class DecoratedRegexURLResolver(URLResolver):
    def resolve(self, *args, **kwargs):
        result = super(DecoratedRegexURLResolver, self).resolve(*args, **kwargs)
        if result:
            result.func = self._decorate_with(result.func)
        return result


def decorated_includes(func, includes):
    """
    Include URLconf from module but apply the specified decorator to each.
    """
    urlconf_module, app_name, namespace = includes
    urlconf_urls = urlconf_module.urlpatterns

    for item in urlconf_urls:
        if isinstance(item, URLPattern):
            item.__class__ = DecoratedURLPattern
            item._decorate_with = func

        elif isinstance(item, URLResolver):
            item.__class__ = DecoratedRegexURLResolver
            item._decorate_with = func

    return urlconf_module, app_name, namespace


legacy_urls = [path("action/logout", views.logout, name="logout_legacy")]

urls = [
    path("register/", views.register, name="register"),
    path("register/complete/", views.register_complete, name="register_complete"),
    re_path(
        r"^register/activate/(?P<activation_token>[-:\w]+)/$",
        views.register_activate,
        name="register_activate",
    ),
    path("register/complete_profile/", views.complete_profile, name="complete_profile"),
    re_path(r"^register/(?P<email>[0-9A-Za-z_\-@+.]+)$", views.register, name="register"),
    re_path(
        r"^resend-new-email-activation/$",
        views.send_new_email_activation,
        name="send_new_email_activation",
    ),
    re_path(
        r"^change-email/activate/(?P<activation_token>[-:\w]+)/$",
        views.change_email_activate,
        name="change_email_activate",
    ),
    re_path(r"^pages/(?P<page_name>[\w-]+)/$", views.pages, name="pages"),
    re_path(
        r"^pages/(?P<page_name>[\w-]+)/(?P<language_code>[\w-]+)/$",
        views.pages,
        name="pages",
    ),
    re_path(
        r"^securitypages/(?P<page_action>[\w-]+)/$",
        views.security_pages,
        name="security_pages",
    ),
    path("securitypages/", views.security_pages, name="security_pages"),
    path("password_reset/", view=PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/sent/", views.password_reset_sent, name="password_reset_sent"),
    re_path(
        r"^password_reset/(?P<pending_user_id>[-:\w]+)/$",
        view=PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("login/", PrimaryLoginView.as_view(), name="login"),
    path("login/pwd/", PasswordLoginView.as_view(), name="login_pwd"),
    path("login/idp/", IDPLoginView.as_view(), name="login_idp"),
    path("login/sent/", views.email_sent, name="login_email_sent"),
    re_path(
        r"^login/email/(?P<pending_user_id>.+)/$",
        views.login_with_email,
        name="login_email",
    ),
    path("login2fa/", Login2faView.as_view(), name="login2fa"),
    re_path(r"^login2fa/(?P<login_step>[\w-]+)/$", Login2faView.as_view(), name="login2fa"),
    re_path(r"^avatar/(?P<user_id>\d+)/(?P<filename>.+)$", api_views.avatar, name="avatar"),
    path("logout/", views.logout, name="logout"),
    re_path(
        r"^profile/delete/(?P<code>.+)/$",
        views.confirm_delete_account,
        name="confirm_delete_account",
    ),
    path("profile/delete/", views.initiate_delete_account, name="delete_account"),
    path("profile/", views.profile, name="profile"),
    path("dashboard/", views.show_dashboard, name="dashboard"),
    path(
        "account/sessions/other/delete/ ",
        view=SessionDeleteOtherView.as_view(),
        name="session_delete_other",
    ),
    re_path(
        r"^account/sessions/(?P<pk>\w+)/delete/$",
        view=SessionDeleteView.as_view(),
        name="session_delete",
    ),
    path(
        "oauth/v2/authorize",
        oauth2_views.AuthorizationView.as_view(),
        name="authorize",
    ),
    path("oauth/v2/token", oauth2_views.TokenView.as_view(), name="token"),
    path(
        "oauth/v2/revoke_token",
        oauth2_views.RevokeTokenView.as_view(),
        name="revoke-token",
    ),
    path("api/users/me", api_views.me, name="me"),
    path("api/users/me/change_avatar", api_views.change_avatar, name="change_avatar"),
    path("api/users/me/remove_avatar", api_views.remove_avatar, name="remove_avatar"),
    path("api/users/me/change_name", api_views.change_name, name="change_name"),
    path("api/users/me/change_email", api_views.change_email, name="change_email"),
    path(
        "api/users/me/change_password",
        api_views.change_password,
        name="change_password",
    ),
    path("api/users/deleted", api_views.deleted_accounts, name="deleted_accounts"),
    path(
        "api/users/get_or_create",
        api_views.get_or_create_user,
        name="get_or_create_user",
    ),
    re_path(
        r"^api/users/fetch_profile/(?P<user_id>\d+)$",
        api_views.fetch_profile,
        name="fetch_profile",
    ),
    re_path(
        r"^api/users/fetch_profile_mail/(?P<email>.+)$",
        api_views.fetch_profile_mail,
        name="fetch_profile_mail",
    ),
    re_path(
        r"^api/users/fetch_avatar/(?P<email>.+)$",
        api_views.fetch_avatar,
        name="fetch_avatar",
    ),
    re_path(
        r"^api/users/register_origin_site/(?P<user_id>\d+)$",
        api_views.register_origin_site,
        name="register_origin_site",
    ),
    re_path(
        r"^api/users/update_origin_site$",
        api_views.update_origin_site,
        name="update_origin_site",
    ),
    path("ht/", include("health_check.urls")),
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
]

tf_urls = [path("", include(tf_urls))]

us_urls = [path("", include("user_sessions.urls", "user_sessions"))]


oidc_urls = [
    re_path(r"^openid/logout/?$", views.oidc_logout, name="oidc_logout"),
    re_path(
        r"^openid/authorize/?$",
        oidc_views.PleioAuthorizeView.as_view(),
        name="authorize",
    ),
    re_path(
        r"^openid/token/?$",
        csrf_exempt(oidc_views.PleioTokenView.as_view()),
        name="token",
    ),
    re_path(
        r"^openid/(?P<provider>[\w-]+)/authenticate/$",
        oidc_views.PleioAuthenticateView.as_view(),
        name="oidc_authentication_init",
    ),
    re_path(
        r"^openid/(?P<provider>[\w-]+)/callback/$",
        oidc_views.PleioCallbackView.as_view(),
        name="oidc_authentication_callback",
    ),
    path(
        "openid/",
        decorated_includes(
            xframe_options_exempt,
            include("oidc_provider.urls", namespace="oidc_provider"),
        ),
    ),
    re_path(
        r"^\.well-known/openid-configuration/$",
        ProviderInfoView.as_view(),
        name="provider_info",
    ),
]

django_urls = [
    path("jsi18n", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("i18n/", include("django.conf.urls.i18n")),
]

saml_urls = [
    re_path(r"^saml/sso/(?P<idp_shortname>[\w-]+)/$", saml_views.sso, name="saml_sso"),
    path("saml/acs/", saml_views.acs, name="saml_acs"),
    path("saml/info/", saml_views.info, name="saml_info"),
    path("saml/slo/", saml_views.slo, name="saml_slo"),
    path("saml/attrs/", saml_views.attrs, name="saml-attrs"),
    path("saml/metadata/", saml_views.metadata, name="saml-metadata"),
    path("saml/connect/", saml_views.connect_and_login, name="saml-connect"),
    path("saml/connect_new/", SamlConnectLoginView.as_view(), name="saml-connect-new"),
    path("saml/connections/", saml_views.show_connections, name="saml_connections"),
    re_path(
        r"^saml/connection_delete/(?P<pk>\w+)/$",
        saml_views.delete_connection,
        name="saml_connection_delete",
    ),
]

urlpatterns = legacy_urls + urls + tf_urls + us_urls + oidc_urls + django_urls + saml_urls

if settings.DEBUG:
    from core import error_views

    debug_urls = [
        path("error500/", error_views.error_500, name="error500"),
    ]
    urlpatterns += debug_urls
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = "core.error_views.error_500"

reporting/models.py
import uuid

from django.db import models
from django.utils import timezone


class ReportManager(models.Manager):
    def create_report(self, model, queryset, owner):
        Report.objects.values_list()
        return self.create(
            model=model._meta.label,
            subset=[str(pk) for pk in queryset.values_list("pk", flat=True)],
            owner=owner,
            name="%s requested to export %s; %s records" % (owner.name, model._meta.label, queryset.count()),
        )


class Report(models.Model):
    class Meta:
        ordering = ("-created_at",)

    objects = ReportManager()

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=255)
    model = models.CharField(max_length=255)
    subset = models.JSONField()
    created_at = models.DateTimeField(default=timezone.localtime)
    owner = models.ForeignKey("core.User", on_delete=models.CASCADE)
    contents = models.TextField()
    ready = models.BooleanField(default=False)

    @property
    def guid(self):
        return str(self.pk)

    def __str__(self):
        return self.name

    @property
    def filename(self):
        return "%s_%s.csv" % (self.model, self.created_at.strftime("%Y%m%d-%H%M%S"))

themes/generic/templates/base_pages.html
{% load i18n %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% load include_asset %}
{% load settings_value %}
{% get_current_language as LANGUAGE_CODE %}
{% settings_value 'SITE_FAVICON' as SITE_FAVICON %}
{% settings_value 'SITE_LOGO' as SITE_LOGO %}
{% settings_value 'SITE_TITLE' as SITE_TITLE %}
{% settings_value 'DEFAULT_SHOW_DESTINATION' as DEFAULT_SHOW_DESTINATION %}
{% settings_value 'DEFAULT_BACKGROUND_URL' as DEFAULT_BACKGROUND_URL %}
{% settings_value 'DEFAULT_DESTINATION_NAME' as DEFAULT_DESTINATION_NAME %}
{% settings_value 'DEFAULT_DESTINATION_URL' as DEFAULT_DESTINATION_URL %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ SITE_TITLE }}</title>
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
        <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
        <link rel="icon" href="/media/{{ SITE_FAVICON }}">
        {% render_bundle "web" "css" %}
        <script src="https://www.google.com/recaptcha/api.js" async defer></script>
        <script nonce="{{ request.csp_nonce }}">
          function onSubmit(token) {
            document.getElementById("register-form").submit();
          }
        </script>
       </head>
    <body>

            <div class="account--terms">
                {{ page_text }}
            </div>

        <script src="https://www.google.com/recaptcha/api.js"></script>
        <script src="{% static "js/jquery-3.7.0.min.js" %}"></script>
        <script src="{% static "js/materialize-0.97.8.min.js" %}"></script>
        {% render_bundle "web" "js" %}
        {% include 'snipets/analytics.html' %}
    </body>
</html>

themes/generic/templates/dashboard.html
{% extends "base_account.html" %}
{% load user_sessions %}
{% load i18n %}
{% load include_asset %}
{% load settings_value %}
{% load origin_site %}

{% block title %}{% trans "Dashboard" %} · {% endblock %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            {% if 'success' in message.tags %}
                <ul class="messages correct" role="alert">
                    <li>
                        {% include_asset "icons/check.svg" %}
                        <div class="textcolor_primary">{% trans 'Success' %}</div>
                        <div class="textcolor_secondary">{{ message }}</div>
                    </li>
                </ul>
            {% elif 'error' in message.tags %}
                <ul class="messages error" role="alert">
                    <li>
                        {% include_asset "icons/person.svg" %}
                        <div class="textcolor_primary">{% trans 'Error' %}</div>
                        <div class="textcolor_secondary">{{ message }}</div>
                    </li>
                </ul>
            {% endif %}
        {% endfor %}
    {% endif %}


    <div class="account__cards">
        <div class="card ___stretch ___nopadding">
            <h3 class="card__title ___addpadding-side">{% trans "Website overview" %}</h3>
            <fieldset class="___addpadding-side">

                <table class="table ___stretch dashboard-table">
                    <thead>
                    <tr>
                        <th>{% trans "Name" %}</th>
                        <th class="align-right">{% trans "Member since" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for registration in sites %}
                        <tr>
                            <td>
                                <div class="registration-data">
                                    {% when_test registration.origin_site.origin_site_url "(Test)" as test_site_label%}
                                    <div class="site-icon">
                                            <img alt="" src="{{ registration.origin_site.favicon_url }}"
                                                 class="site-icon-image">
                                    </div>
                                    <div class="site-info">
                                        <a class="site-info--title" href="{{ registration.origin_site.origin_site_url }}">{{ registration.origin_site }} {{ test_site_label }}</a><br>
                                        {% if registration.origin_site.origin_site_description %}
                                        <p class="site-info--description" >{{ registration.origin_site.origin_site_description }}</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </td>
                            <td class="align-right"><div class="site-member-since">{{ registration.created_at | date:"d-m-Y" }}</div></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <br/>

            </fieldset>

        </div>
    </div>

{% endblock %}

themes/generic/templates/password_reset_sent.html
{% extends "base.html" %}
{% load i18n %}
{% load include_asset %}
{% load settings_value %}

{% block title %}{% trans "Forgot password" %} · {% endblock %}

{% block content %}
    <div class="login__step-title">
        <div>
            <h2>{% trans "Forgot password" %}</h2>
            <p>{% trans "of your " %}{% settings_value 'SITE_TITLE' %}{% trans " account" %}</p>
        </div>
        <img alt="" src="/static/images/logo-icon.svg" class="login__step-icon"/>
    </div>

    {% include 'login/messages.html' %}
    <br/>

    <ul class="messages correct" role="alert">
        <li class="messages__link">
            {% include_asset "icons/email.svg" %}
            <div class="textcolor_primary">{% trans "Email sent" %}</div>
            <div class="textcolor_secondary">{% trans "When the address is registered in our system you will receive an email with a link to configure a new password." %} </div>
        </li>
    </ul>

    <div class="register__buttons">
        <a href="{% url 'login' %}" class="button ___stretch ___white ___outline"> {% trans "Log in" %}</a>
    </div>

    <ul class="messages info" role="alert">
        <li class="messages__link">
            <a href="mailto: {{ EMAIL_SUPPORT }}">
                {% include_asset "icons/help-outline.svg" %}
                <div class="textcolor_primary">{% trans "Need help?" %}</div>
                <div class="textcolor_secondary">{% trans "Email" %} {{ EMAIL_SUPPORT }}</div>
            </a>
        </li>
    </ul>
{% endblock %}

themes/generic/templates/profile.html
{% extends "base_account.html" %}
{% load i18n %}
{% load include_asset %}
{% load show_government_badge %}
{% load settings_value %}
{% load avatars %}
{% load wcag_complience %}

{% block title %}{% trans "Profile" %} · {% endblock %}

{% block content %}
    <h2>{% trans "Profile" %}</h2>

    {% if messages %}
      {% for message in messages %}
        {% if 'success' in message.tags %}
            <ul class="messages correct" role="alert">
                <li>
                    {% include_asset "icons/check.svg" %}
                    {% if 'password' in message.tags %}
                        <div class="textcolor_primary">{% trans "Password changed" %}</div>
                        <div class="textcolor_secondary">{% trans "You can now login using your new password" %}</div>
                    {% elif 'email' in message.tags %}
                        <div class="textcolor_primary">{% trans "Email address changed" %}</div>
                        <div class="textcolor_secondary">{% trans "You can now login using your new email address" %}</div>
                    {% elif 'profile' in message.tags %}
                        <div class="textcolor_primary">{% trans "Profile changed" %}</div>
                        <div class="textcolor_secondary">{% trans "Your profile has been changed" %}</div>
                    {% else %}
                        <div class="textcolor_primary">{% trans 'Success' %}</div>
                        <div class="textcolor_secondary">{{ message }}</div>
                    {% endif %}
                </li>
            </ul>
        {% elif 'info' in message.tags %}
            <ul class="messages info" role="alert">
                <li>
                    {% include_asset "icons/lock.svg" %}
                    {% if 'email_sent' in message.tags %}
                        <div class="textcolor_primary">{% trans 'Email sent' %}</div>
                        <div class="textcolor_secondary">{% trans "Please check your inbox to validate the change." %}</div>
                    {% elif 'account_created' in message.tags %}
                        <div class="textcolor_primary">{% trans 'Account created' %}</div>
                        <div class="textcolor_secondary">{% trans "Please check your inbox to set your password." %}</div>
                    {% else %}
                        <div class="textcolor_primary">{% trans 'Info' %}</div>
                        <div class="textcolor_secondary">{{ message }}</div>
                    {% endif %}
                </li>
            </ul>
        {% elif 'error' in message.tags %}
            <ul class="messages error" role="alert">
                <li>
                    {% include_asset "icons/person.svg" %}
                    <div class="textcolor_primary">{% trans 'Error' %}</div>
                    <div class="textcolor_secondary">{{ message }}</div>
                </li>
            </ul>
        {% endif %}
      {% endfor %}
      <p></p>
    {% endif %}

    <form id="profile-form" enctype="multipart/form-data" method="post" action="." novalidate>
        <div class="account__cards">
            <div class="card ___nopadding">
                {% csrf_token %}
                <h3 class="card__title ___addpadding-side">{% trans "Your details" %}</h3>

                <ul class="messages error" role="alert">
                    {% for error in form.non_field_errors %}
                        <li>
                        {% include_asset "icons/person.svg" %}
                        <div class="textcolor_primary">{% trans "Invalid email address." %}</div>
                        <div class="textcolor_secondary">{{ error }}</div>
                        </li>
                    {% endfor %}
                </ul>
                <p></p><p></p>

                <fieldset class="___addpadding-side">
                    <div class="input-field">
                        <label for="id_name">{% trans "Name" %}</label>
                        {{ form.name|aria_invalid}}
                        {% include "snipets/form_errors.html" with field=form.name %}
                    </div>
                    <div class="input-field">
                        <label for="id_email">{% trans "Email" %}</label>
                        {{ form.email|aria_invalid}}
                        {% include "snipets/form_errors.html" with field=form.email %}
                        {% show_government_badge form.email.value as show_badge %}
                        {% if show_badge %}
                            <span class="badge green __uppercase">{% include_asset "icons/check.svg" %}{% trans "Government" %}</span>
                        {% endif %}
                    </div>
                    {% if text_change_pending %}
                        <div>
                            {{ text_change_pending }}<b>{{ text_email }}</b><br>
                            {% trans "Please check your inbox to validate the change." %}<br>
                            {% trans "Click " %}<a href="{% url 'send_new_email_activation' %}"><b>{% trans "here" %}</b></a> {% trans "to resend the confirmation e-mail." %}
                        </div>
                    {% endif %}

            </fieldset>
                <div class="card__action ___addpadding-side">
                    <button name="update" class="button ___clear" type="submit">{% trans "Save" %}</button>
                </div>
            </div>

            <div class="card ___nopadding">
                <h3 class="card__title ___addpadding-side">{% trans "Avatar" %}</h3>
                <div class="account-user__pickavatar ___addpadding-side">
                    <div class="input-field">
                        {% if request.user.avatar %}
                            <img src="{% avatar_url request.user "large" %}" alt="{% trans 'Avatar' %}" border=0 class="account-user__avatar">
                            <input id="avatar-clear_id" name="avatar-clear" type="checkbox" tabindex="-1">
                        {% else %}
                            <img src="/static/icons/person.svg" alt="{% trans 'Avatar' %}" border=0 class="account-user__avatar">
                        {% endif %}

                        {{ form.errors.avatar }}
                        <input id="id_avatar" name="avatar" type="file" accept=".jpg, .jpeg, .png">
                    </div>
                    <button id="avatar-change-button" class="button" type="button">{% trans "Choose an avatar" %}</button>
                </div>
                <div class="card__action ___addpadding-side">
                    <button id="avatar-clear-button" class="button ___clear" type="button" name="update">{% trans "Remove avatar" %}</button>
                </div>
            </div>
            <a href="{% url 'delete_account' %}" class="card ___nopadding button ___error">
                {% trans "Delete my account" %}
            </a>
        </div>
    </form>

    <script nonce="{{ request.csp_nonce }}">
        document.addEventListener("DOMContentLoaded", (event) => {
            const profileForm = document.getElementById("profile-form");
            const avatarChangeButton = document.getElementById("avatar-change-button");
            const avatarChangeInput = document.getElementById("id_avatar");
            const avatarClearButton = document.getElementById("avatar-clear-button");
            const avatarClearInput = document.getElementById("avatar-clear_id");

            avatarChangeButton.addEventListener("click", () => {
                avatarChangeInput.click();
            });

            avatarChangeInput.addEventListener("change", () => {
                profileForm.submit();
            });

            avatarClearButton.addEventListener("click", () => {
                avatarClearInput.checked = true;
                profileForm.submit();
            });
        });
    </script>
{% endblock %}

themes/generic/templates/register.html
{% extends "base.html" %}
{% load i18n %}
{% load include_asset %}
{% load settings_value %}
{% load absolute_url %}
{% load wcag_complience %}

{% block title %}{% trans "Register an account" %} · {% endblock %}

{% block content %}

<form id="credentials-form" method="post" novalidate>
    {% csrf_token %}
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>

    <div class="login__step-title">
        <div>
            <h2>{% trans "Register an account" %}</h2>
            <div></div>
        </div>
        <img alt="" src="/static/images/logo-icon.svg" class="login__step-icon"/>
    </div>
    {% if messages %}
        {% for message in messages %}
            {% if 'success' in message.tags %}
                <ul class="messages correct" role="alert">
                    <li>
                        {% include_asset "icons/check.svg" %}
                        <div class="textcolor_primary">{% trans 'Success' %}</div>
                        <div class="textcolor_secondary">{{ message }}</div>
                    </li>
                </ul>
            {% elif 'info' in message.tags %}
                <ul class="messages info" role="alert">
                    <li>
                    {% include_asset "icons/lock.svg" %}
                        <div class="textcolor_primary">{% trans "Information" %}</div>
                        <div class="textcolor_secondary">{{ message }}</div>
                    </li>
                </ul>
            {% elif 'error' in message.tags %}
                <ul class="messages error" role="alert">
                    <li>
                        {% include_asset "icons/person.svg" %}
                        {% if 'cant_proceed' in message.tags %}
                            <div class="textcolor_primary">{% trans "Registration at Pleio failed." %}</div>
                            <div class="textcolor_secondary">{% trans "Please contact the site owner or your contact person to complete the registration process." %}</div>
                       {% else %}
                            <div class="textcolor_primary">{% trans 'Error' %}</div>
                            <div class="textcolor_secondary">{{ message }}</div>
                        {% endif %}
                    </li>
                </ul>
            {% endif %}
        {% endfor %}
    {% endif %}

    <ul class="messages error" role="alert">
            {% for error in form.non_field_errors %}
            <li>
                {% include_asset "icons/person.svg" %}
                {% if error == 'captcha_mismatch' %}
                    <div class="textcolor_primary">{% trans "Login failed." %}</div>
                    <div class="textcolor_secondary">{% trans "Please check Google captcha." %}</div>
                {% else %}
                    <div class="textcolor_primary">{% trans 'Error' %}</div>
                    <div class="textcolor_secondary">{{ error }}</div>
                {% endif %}
            </li>
        {% endfor %}
</ul>

    <fieldset>
        <div class="input-field">
            <label for="id_name">{% trans "First- and lastname" %}</label>
            {{ form.name|aria_invalid}}
            {% include "snipets/form_errors.html" with field=form.name %}
        </div>
        <div class="input-field">
            <label for="id_email">{% trans "Email" %}</label>
            {{ form.email|aria_invalid}}
            {% include "snipets/form_errors.html" with field=form.email %}
        </div>
        <div class="input-field">
            <label for="id_password1">{% trans "Password (minimum of " %}{% settings_value "MINIMAL_PASSWORD_LENGTH" %}{% trans " characters)"%}</label>
            {{ form.password1|aria_invalid}}
            {% include "snipets/form_errors.html" with field=form.password1 %}
            <button type="button" class="password__toggle">
                                <div class="password__toggle-on">{% include_asset "icons/eye.svg" %}<span class="hide-visually">Verberg wachtwoord</span></div>
                                <div class="password__toggle-off">{% include_asset "icons/eye-off.svg" %}<span class="hide-visually">Toon wachtwoord</span></div>
                            </button>
            <p class="capslock"></p>
        </div>
        <div class="input-field">
            <label for="id_password2">{% trans "Password (again)" %}</label>
            {{ form.password2|aria_invalid}}
            {% include "snipets/form_errors.html" with field=form.password2 %}
            <button type="button" class="password__toggle">
                                <div class="password__toggle-on">{% include_asset "icons/eye.svg" %}<span class="hide-visually">Verberg wachtwoord</span></div>
                                <div class="password__toggle-off">{% include_asset "icons/eye-off.svg" %}<span class="hide-visually">Toon wachtwoord</span></div>
                            </button>
            <p class="capslock"></p>
        </div>

        <div class="register__checks">
            <div class="register__check">
                {{ form.accepted_terms|aria_invalid}}
                <label for="id_accepted_terms">{% trans "I agree with "%}
                {% if SITE_TERMS %}
                    <a href="{% absolute_url SITE_TERMS %}" target=_blank>
                {% else %}
                    <a target=_blank href="/pages/terms">
                {% endif %}
                {% trans "the general terms" %}</a></label>
            </div>
            {% include "snipets/form_errors.html" with field=form.accepted_terms %}
        </div>

        {% settings_value 'GOOGLE_RECAPTCHA_SITE_KEY' as recaptcha_site_key %}

        <div class="register__buttons">
            {% if recaptcha_site_key %}
                <button name="register" class="g-recaptcha button ___stretch ___active" data-sitekey="{{ recaptcha_site_key }}" data-callback='onSubmit'>{% trans "Register" %}</button>
            {% else %}
                <button name="register" class="button ___stretch ___active" type="submit">{% trans "Register" %}</button>
            {% endif %}
            <button name="button_login" class="button ___stretch ___white ___outline" type="submit">{% trans "Log in" %}</button>
        </div>

    </fieldset>
</form>

{% endblock %}